services:
  postgres:
    image: postgres
    container_name: database-postgres-test
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: db_test
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
