import Head from 'next/head'
import { Navbar } from '../ui'
import styles from '@/styles/layouts/LayoutHome.module.css'

type Props = {
  children: JSX.Element
}

export function LayoutHome({ children }: Props) {
  return (
    <div>
      <Head>
        <title>Base App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Navbar />
      <main className={styles.container}>{children}</main>
    </div>
  )
}
